# based on Minima theme https://github.com/jekyll/minima

# Notes: 
# - fig include, {% include figure.html file="my-cat.jpg" alt="cat" caption="My cat" width="50%" %}
# - pages with "nav: true" in front matter will be in header nav
# - use environment variable on build command to include analytics: JEKYLL_ENV=production jekyll build

# site settings
title: MySQL Heatwave Workshop
description: "Learn about MySQL Heatwave."
keywords: "MySQL, Heatwave, Oracle, ML, ridha chahed"

# author settings for cc-by
author: Ridha Chahed
pub_year: 2024
github_username: ridhachahed

# add the full url for the github repository
repo: "https://github.com/ridhachahed/heatwave-workshop-website"

# urls
# your gh-pages url: https://username.github.io
url: https://ridhachahed.github.io
# your repository name: /repository
baseurl: /heatwave-workshop-website

# analytics if desired (and use environment variable on build command)
google_analytics:

# defaults (to simplify front matter)
defaults:
  - scope:
      path: ""
    values:
      layout: default

# Build settings
markdown: kramdown
